from jogo import PERSONAGEM

# É DE EXTREMA IMPORTÂNCIA NÃO MUDAR O NOME DA VARIÁVEL
# ELA É FUNDAMENTAL PARA O SAVE FUNCIONAR
jogador = PERSONAGEM("ALTERE O NOME")

# SISTEMA DE PARAR CRIADO
while jogador.jogando == True:
    jogador.DECISAO()
